
version: '3'

services:
   db:
     build: ./db
     volumes:
       - db_data2:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: olog
       MYSQL_DATABASE: olog
       MYSQL_USER: olog
       MYSQL_PASSWORD: olog
     ports:
       - "3306:3306"

   glassfish:
     depends_on:
       - db
     build: ./glassfish
     ports:
       - "18080:8080"
       - "8081:8081"
       - "14848:4848"
     restart: always
     environment:
       - DATABASE_HOST=db
       - DATABASE_PORT=3306
       - GLASSFISH_PASS="password"

   openldap:
     build: ./ldap
     container_name: openldap
     environment:
       LDAP_LOG_LEVEL: "256"
       LDAP_ORGANISATION: "Example Inc."
       LDAP_DOMAIN: "example.org"
       LDAP_BASE_DN: ""
       LDAP_ADMIN_PASSWORD: "admin"
       LDAP_CONFIG_PASSWORD: "config"
       LDAP_READONLY_USER: "false"
       LDAP_RFC2307BIS_SCHEMA: "false"
       LDAP_BACKEND: "hdb"
       LDAP_TLS: "true"
       LDAP_TLS_CRT_FILENAME: "ldap.crt"
       LDAP_TLS_KEY_FILENAME: "ldap.key"
       LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
       LDAP_TLS_ENFORCE: "false"
       LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
       LDAP_TLS_PROTOCOL_MIN: "3.1"
       LDAP_TLS_VERIFY_CLIENT: "demand"
       LDAP_REPLICATION: "false"
       KEEP_EXISTING_CONFIG: "false"
       LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
       LDAP_SSL_HELPER_PREFIX: "ldap"
     tty: true
     stdin_open: true
     volumes:
       - /var/lib/ldap
       - /etc/ldap/slapd.d
       - /container/service/slapd/assets/certs/
     ports:
       - "389:389"
       - "636:636"
     domainname: "example.org" # important: same as hostname
     hostname: "example.org"

volumes:
    db_data2:
